language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SCRUTINIZER_REPORT=true
    - php: 7.0

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - phpenv rehash

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - php vendor/bin/phpcs -n --standard=PSR2 --ignore=vendor .

after_script: >
  [ "$SCRUTINIZER_REPORT" = true ]
  && wget https://scrutinizer-ci.com/ocular.phar
  && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
